Sundsvallskommun/web-app-intric-backend

admin/src/components/edit-resource/edit-resource-array.component.tsx
Fix for new strict lint rule. Caused build errors.
=> fix: typing error in admin

backend/src/controllers/space.controller.ts
=> bad : before id

backend/src/controllers/user.controller.ts, backend/src/server.ts
=> feat: user controller / get me

backend/src/data-contracts/intric/data-contracts.ts, backend/src/dtos/assistant.dto.ts
=> updated assistant contracts and dtos to latest intric version

backend/src/controllers/file.controller.ts, backend/src/server.ts
=> feat: added file controller

backend/src/controllers/query.controller.ts
=> feat: attach files to query

backend/src/services/intric-api-key.service.ts
=> fix: issues with apikey sent as 'undefined' string

backend/src/controllers/query.controller.ts
Sometimes bad data would be sent to intric
=> fix: query bug

backend/src/controllers/space.controller.ts
=> feat: create space assistant

backend/package.json, backend/src/data-contracts/intric/data-contracts.ts, backend/yarn.lock
=> updated contracts

backend/src/app.ts, backend/src/controllers/assistant.controller.ts, backend/src/controllers/space.controller.ts
[https://jira.sundsvall.se/browse/AI-234](https://jira.sundsvall.se/browse/AI-234)
=> feat: batch get assistants and spaces

backend/src/controllers/group.controller.ts, backend/src/dtos/group.dto.ts
=> fix: updated groups to intric updates

backend/src/controllers/assistant.controller.ts, backend/src/dtos/assistant.dto.ts, backend/src/responses/assistant.response.ts, backend/src/responses/intric/assistant.response.ts, backend/src/responses/intric/common.ts, backend/src/responses/intric/file.response.ts, backend/src/responses/intric/group.response.ts, backend/src/responses/intric/info-blob.response.ts, backend/src/responses/intric/session.response.ts, backend/src/responses/intric/website.response.ts
[https://jira.sundsvall.se/browse/AI-239](https://jira.sundsvall.se/browse/AI-239)
=> feat: classes and swagger for intric assistants

backend/src/controllers/azure.controller.ts, backend/src/dtos/azure.dto.ts, backend/src/interfaces/azure.interface.ts, backend/src/responses/azure.response.ts, backend/src/services/azure.service.ts
=> feat: types and swaggers for azure controller

backend/src/controllers/info-blob.controller.ts
[https://jira.sundsvall.se/browse/AI-244](https://jira.sundsvall.se/browse/AI-244)
=> feat: swagger and validation for info blobs

backend/package.json, backend/src/config/api-config.ts, backend/src/config/index.ts, backend/src/controllers/health.controller.ts, backend/src/data-contracts/simulatorserver/data-contracts.ts, backend/src/responses/health.controller.ts, backend/src/swagger-typescript-api.ts
=> feat: health contract and swagger

backend/src/controllers/user.controller.ts, backend/src/responses/intric/assistant.response.ts, backend/src/responses/intric/user.response.ts
[https://jira.sundsvall.se/browse/AI-247](https://jira.sundsvall.se/browse/AI-247)
=> feat: Intric user swagger

backend/src/controllers/query.controller.ts, backend/src/dtos/assistant.dto.ts, backend/src/interfaces/feedback.ts, backend/src/responses/intric/common.ts, backend/src/responses/intric/info-blob.response.ts, backend/src/responses/intric/query.response.ts, backend/src/responses/intric/session.response.ts
=> feat: swagger and validation for query

admin/src/utils/use-localstorage.hook.ts
[UF-15195](https://jira.sundsvall.se/browse/UF-15195)
=> fix(admin): changed to sessionstorage

admin/package.json, admin/src/components/edit-resource/edit-resource-array.component.tsx, admin/src/components/edit-resource/edit-resource-object.component.tsx, admin/src/components/edit-resource/edit-resource.component.tsx, admin/src/config/resources.ts, admin/src/data-contracts/backend/Api.ts, admin/src/data-contracts/backend/data-contracts.ts, admin/src/pages/assistants/[id].tsx, admin/yarn.lock
[AI-252](https://jira.sundsvall.se/browse/AI-252)
=> fix: updated contracts and fixed build errors

backend/src/controllers/query.controller.ts
=> fix: issues with sending response

admin/src/components/list-resources/list-resources.tsx
=> fix: missing property for rendering edit links
